<?php

/**
 * AxytosCommonPublicAPIEnumsProofOfInterest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package Axytos\FinancialServices\OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Axytos API
 *
 * Note: Please provide proper values in \"Try it out\". See schemas and endpoint description for possible values. <br/>DateTimes should always be provided in UTC and with the timezone attached, see ISO-8601 (example: 2021-10-13T20:00:30Z)
 *
 * The version of the OpenAPI document: v1
 * Contact:
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.1.0-SNAPSHOT
 */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
namespace Axytos\FinancialServices\OpenAPI\Client\Model;

use Axytos\FinancialServices\OpenAPI\Client\ObjectSerializer;
/**
 * AxytosCommonPublicAPIEnumsProofOfInterest Class Doc Comment
 *
 * @category Class
 * @package Axytos\FinancialServices\OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AxytosCommonPublicAPIEnumsProofOfInterest
{
    /**
     * Possible values of this enum
     */
    const AAA = 'AAA';
    const AAB = 'AAB';
    const BAB = 'BAB';
    const BAC = 'BAC';
    const AAE = 'AAE';
    const AAF = 'AAF';
    const AAG = 'AAG';
    const AAH = 'AAH';
    const AAI = 'AAI';
    const BAA = 'BAA';
    const AAJ = 'AAJ';
    const AAK = 'AAK';
    const DAA = 'DAA';
    const DAB = 'DAB';
    const DAD = 'DAD';
    const DAC = 'DAC';
    const AAL = 'AAL';
    const EAA = 'EAA';
    const AAM = 'AAM';
    const EAB = 'EAB';
    const FAA = 'FAA';
    const FAB = 'FAB';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [self::AAA, self::AAB, self::BAB, self::BAC, self::AAE, self::AAF, self::AAG, self::AAH, self::AAI, self::BAA, self::AAJ, self::AAK, self::DAA, self::DAB, self::DAD, self::DAC, self::AAL, self::EAA, self::AAM, self::EAB, self::FAA, self::FAB];
    }
}
