<?php

/**
 * AxytosCommonPublicAPIModelsPaymentControlPaymentControlConfirmRequest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package Axytos\FinancialServices\OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Axytos API
 *
 * Note: Please provide proper values in \"Try it out\". See schemas and endpoint description for possible values. <br/>DateTimes should always be provided in UTC and with the timezone attached, see ISO-8601 (example: 2021-10-13T20:00:30Z)
 *
 * The version of the OpenAPI document: v1
 * Contact:
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.1.0-SNAPSHOT
 */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
namespace Axytos\FinancialServices\OpenAPI\Client\Model;

use ArrayAccess;
use Axytos\FinancialServices\OpenAPI\Client\ObjectSerializer;
/**
 * AxytosCommonPublicAPIModelsPaymentControlPaymentControlConfirmRequest Class Doc Comment
 *
 * @category Class
 * @package Axytos\FinancialServices\OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AxytosCommonPublicAPIModelsPaymentControlPaymentControlConfirmRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    const DISCRIMINATOR = null;
    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'Axytos.Common.PublicAPI.Models.PaymentControl.PaymentControlConfirmRequest';
    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = ['custom_reference' => 'string', 'personal_data' => 'Axytos\FinancialServices\OpenAPI\Client\Model\AxytosCommonDebitorCustomerData', 'invoice_address' => 'Axytos\FinancialServices\OpenAPI\Client\Model\AxytosCommonPublicAPIModelsCommonInvoiceAddress', 'delivery_address' => 'Axytos\FinancialServices\OpenAPI\Client\Model\AxytosCommonPublicAPIModelsCommonDeliveryAddress', 'basket' => 'Axytos\FinancialServices\OpenAPI\Client\Model\AxytosCommonPublicAPIModelsPaymentControlPaymentControlBasket', 'payment_control_response' => 'Axytos\FinancialServices\OpenAPI\Client\Model\AxytosCommonPublicAPIModelsPaymentControlPaymentControlResponse', 'payment_type' => 'string', 'payment_type_security' => 'Axytos\FinancialServices\OpenAPI\Client\Model\AxytosCommonPublicAPIEnumsPaymentTypeSecurity'];
    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = ['custom_reference' => null, 'personal_data' => null, 'invoice_address' => null, 'delivery_address' => null, 'basket' => null, 'payment_control_response' => null, 'payment_type' => null, 'payment_type_security' => null];
    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }
    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }
    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = ['custom_reference' => 'customReference', 'personal_data' => 'personalData', 'invoice_address' => 'invoiceAddress', 'delivery_address' => 'deliveryAddress', 'basket' => 'basket', 'payment_control_response' => 'paymentControlResponse', 'payment_type' => 'paymentType', 'payment_type_security' => 'paymentTypeSecurity'];
    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = ['custom_reference' => 'setCustomReference', 'personal_data' => 'setPersonalData', 'invoice_address' => 'setInvoiceAddress', 'delivery_address' => 'setDeliveryAddress', 'basket' => 'setBasket', 'payment_control_response' => 'setPaymentControlResponse', 'payment_type' => 'setPaymentType', 'payment_type_security' => 'setPaymentTypeSecurity'];
    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = ['custom_reference' => 'getCustomReference', 'personal_data' => 'getPersonalData', 'invoice_address' => 'getInvoiceAddress', 'delivery_address' => 'getDeliveryAddress', 'basket' => 'getBasket', 'payment_control_response' => 'getPaymentControlResponse', 'payment_type' => 'getPaymentType', 'payment_type_security' => 'getPaymentTypeSecurity'];
    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }
    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }
    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }
    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }
    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];
    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['custom_reference'] = isset($data['custom_reference']) ? $data['custom_reference'] : null;
        $this->container['personal_data'] = isset($data['personal_data']) ? $data['personal_data'] : null;
        $this->container['invoice_address'] = isset($data['invoice_address']) ? $data['invoice_address'] : null;
        $this->container['delivery_address'] = isset($data['delivery_address']) ? $data['delivery_address'] : null;
        $this->container['basket'] = isset($data['basket']) ? $data['basket'] : null;
        $this->container['payment_control_response'] = isset($data['payment_control_response']) ? $data['payment_control_response'] : null;
        $this->container['payment_type'] = isset($data['payment_type']) ? $data['payment_type'] : null;
        $this->container['payment_type_security'] = isset($data['payment_type_security']) ? $data['payment_type_security'] : null;
    }
    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];
        if ($this->container['invoice_address'] === null) {
            $invalidProperties[] = "'invoice_address' can't be null";
        }
        if ($this->container['basket'] === null) {
            $invalidProperties[] = "'basket' can't be null";
        }
        if ($this->container['payment_control_response'] === null) {
            $invalidProperties[] = "'payment_control_response' can't be null";
        }
        if ($this->container['payment_type_security'] === null) {
            $invalidProperties[] = "'payment_type_security' can't be null";
        }
        return $invalidProperties;
    }
    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }
    /**
     * Gets custom_reference
     *
     * @return string|null
     */
    public function getCustomReference()
    {
        return $this->container['custom_reference'];
    }
    /**
     * Sets custom_reference
     *
     * @param string|null $custom_reference custom_reference
     *
     * @return self
     */
    public function setCustomReference($custom_reference)
    {
        $this->container['custom_reference'] = $custom_reference;
        return $this;
    }
    /**
     * Gets personal_data
     *
     * @return \Axytos\FinancialServices\OpenAPI\Client\Model\AxytosCommonDebitorCustomerData|null
     */
    public function getPersonalData()
    {
        return $this->container['personal_data'];
    }
    /**
     * Sets personal_data
     *
     * @param \Axytos\FinancialServices\OpenAPI\Client\Model\AxytosCommonDebitorCustomerData|null $personal_data personal_data
     *
     * @return self
     */
    public function setPersonalData($personal_data)
    {
        $this->container['personal_data'] = $personal_data;
        return $this;
    }
    /**
     * Gets invoice_address
     *
     * @return \Axytos\FinancialServices\OpenAPI\Client\Model\AxytosCommonPublicAPIModelsCommonInvoiceAddress
     */
    public function getInvoiceAddress()
    {
        return $this->container['invoice_address'];
    }
    /**
     * Sets invoice_address
     *
     * @param \Axytos\FinancialServices\OpenAPI\Client\Model\AxytosCommonPublicAPIModelsCommonInvoiceAddress $invoice_address invoice_address
     *
     * @return self
     */
    public function setInvoiceAddress($invoice_address)
    {
        $this->container['invoice_address'] = $invoice_address;
        return $this;
    }
    /**
     * Gets delivery_address
     *
     * @return \Axytos\FinancialServices\OpenAPI\Client\Model\AxytosCommonPublicAPIModelsCommonDeliveryAddress|null
     */
    public function getDeliveryAddress()
    {
        return $this->container['delivery_address'];
    }
    /**
     * Sets delivery_address
     *
     * @param \Axytos\FinancialServices\OpenAPI\Client\Model\AxytosCommonPublicAPIModelsCommonDeliveryAddress|null $delivery_address delivery_address
     *
     * @return self
     */
    public function setDeliveryAddress($delivery_address)
    {
        $this->container['delivery_address'] = $delivery_address;
        return $this;
    }
    /**
     * Gets basket
     *
     * @return \Axytos\FinancialServices\OpenAPI\Client\Model\AxytosCommonPublicAPIModelsPaymentControlPaymentControlBasket
     */
    public function getBasket()
    {
        return $this->container['basket'];
    }
    /**
     * Sets basket
     *
     * @param \Axytos\FinancialServices\OpenAPI\Client\Model\AxytosCommonPublicAPIModelsPaymentControlPaymentControlBasket $basket basket
     *
     * @return self
     */
    public function setBasket($basket)
    {
        $this->container['basket'] = $basket;
        return $this;
    }
    /**
     * Gets payment_control_response
     *
     * @return \Axytos\FinancialServices\OpenAPI\Client\Model\AxytosCommonPublicAPIModelsPaymentControlPaymentControlResponse
     */
    public function getPaymentControlResponse()
    {
        return $this->container['payment_control_response'];
    }
    /**
     * Sets payment_control_response
     *
     * @param \Axytos\FinancialServices\OpenAPI\Client\Model\AxytosCommonPublicAPIModelsPaymentControlPaymentControlResponse $payment_control_response payment_control_response
     *
     * @return self
     */
    public function setPaymentControlResponse($payment_control_response)
    {
        $this->container['payment_control_response'] = $payment_control_response;
        return $this;
    }
    /**
     * Gets payment_type
     *
     * @return string|null
     */
    public function getPaymentType()
    {
        return $this->container['payment_type'];
    }
    /**
     * Sets payment_type
     *
     * @param string|null $payment_type payment_type
     *
     * @return self
     */
    public function setPaymentType($payment_type)
    {
        $this->container['payment_type'] = $payment_type;
        return $this;
    }
    /**
     * Gets payment_type_security
     *
     * @return \Axytos\FinancialServices\OpenAPI\Client\Model\AxytosCommonPublicAPIEnumsPaymentTypeSecurity
     */
    public function getPaymentTypeSecurity()
    {
        return $this->container['payment_type_security'];
    }
    /**
     * Sets payment_type_security
     *
     * @param \Axytos\FinancialServices\OpenAPI\Client\Model\AxytosCommonPublicAPIEnumsPaymentTypeSecurity $payment_type_security payment_type_security
     *
     * @return self
     */
    public function setPaymentTypeSecurity($payment_type_security)
    {
        $this->container['payment_type_security'] = $payment_type_security;
        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }
    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }
    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }
    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }
    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }
    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this), \JSON_PRETTY_PRINT);
    }
    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
