<?php
/**
 * AxytosCommonEnumsPaymentType
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Axytos\FinancialServicesAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Axytos API
 *
 * Note: Please provide proper values in \"Try it out\". See schemas and endpoint description for possible values. <br/>DateTimes should always be provided in UTC and with the timezone attached, see ISO-8601 (example: 2021-10-13T20:00:30Z)
 *
 * The version of the OpenAPI document: v1
 * Contact: 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Axytos\FinancialServicesAPI\Client\Model;
use \Axytos\FinancialServicesAPI\Client\ObjectSerializer;

/**
 * AxytosCommonEnumsPaymentType Class Doc Comment
 *
 * @category Class
 * @package  Axytos\FinancialServicesAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AxytosCommonEnumsPaymentType
{
    /**
     * Possible values of this enum
     */
    public const INVOICE = 'Invoice';

    public const DIRECT_DEBIT = 'DirectDebit';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::INVOICE,
            self::DIRECT_DEBIT
        ];
    }
}


