<?php
/**
 * AxytosCommonPublicAPIModelsOrderOrderPreCheckRequest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Axytos\FinancialServicesAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Axytos API
 *
 * Note: Please provide proper values in \"Try it out\". See schemas and endpoint description for possible values. <br/>DateTimes should always be provided in UTC and with the timezone attached, see ISO-8601 (example: 2021-10-13T20:00:30Z)
 *
 * The version of the OpenAPI document: v1
 * Contact: 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Axytos\FinancialServicesAPI\Client\Model;

use \ArrayAccess;
use \Axytos\FinancialServicesAPI\Client\ObjectSerializer;

/**
 * AxytosCommonPublicAPIModelsOrderOrderPreCheckRequest Class Doc Comment
 *
 * @category Class
 * @package  Axytos\FinancialServicesAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AxytosCommonPublicAPIModelsOrderOrderPreCheckRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Axytos.Common.PublicAPI.Models.Order.OrderPreCheckRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'request_mode' => '\Axytos\FinancialServicesAPI\Client\Model\AxytosCommonPublicAPIEnumsPaymentControlRequestMode',
        'custom_reference' => 'string',
        'personal_data' => '\Axytos\FinancialServicesAPI\Client\Model\AxytosCommonPublicAPIModelsCommonCustomerDataRequestModel',
        'proof_of_interest' => '\Axytos\FinancialServicesAPI\Client\Model\AxytosCommonPublicAPIEnumsProofOfInterest',
        'selected_payment_type' => 'string',
        'payment_type_security' => '\Axytos\FinancialServicesAPI\Client\Model\AxytosCommonPublicAPIEnumsPaymentTypeSecurity',
        'invoice_address' => '\Axytos\FinancialServicesAPI\Client\Model\AxytosCommonPublicAPIModelsCommonInvoiceAddress',
        'delivery_address' => '\Axytos\FinancialServicesAPI\Client\Model\AxytosCommonPublicAPIModelsCommonDeliveryAddress',
        'basket' => '\Axytos\FinancialServicesAPI\Client\Model\AxytosCommonPublicAPIModelsOrderBasket',
        'order_precheck_response' => '\Axytos\FinancialServicesAPI\Client\Model\AxytosCommonPublicAPIModelsPaymentControlOrderPrecheckResponse'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'request_mode' => null,
        'custom_reference' => null,
        'personal_data' => null,
        'proof_of_interest' => null,
        'selected_payment_type' => null,
        'payment_type_security' => null,
        'invoice_address' => null,
        'delivery_address' => null,
        'basket' => null,
        'order_precheck_response' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'request_mode' => 'requestMode',
        'custom_reference' => 'customReference',
        'personal_data' => 'personalData',
        'proof_of_interest' => 'proofOfInterest',
        'selected_payment_type' => 'selectedPaymentType',
        'payment_type_security' => 'paymentTypeSecurity',
        'invoice_address' => 'invoiceAddress',
        'delivery_address' => 'deliveryAddress',
        'basket' => 'basket',
        'order_precheck_response' => 'orderPrecheckResponse'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'request_mode' => 'setRequestMode',
        'custom_reference' => 'setCustomReference',
        'personal_data' => 'setPersonalData',
        'proof_of_interest' => 'setProofOfInterest',
        'selected_payment_type' => 'setSelectedPaymentType',
        'payment_type_security' => 'setPaymentTypeSecurity',
        'invoice_address' => 'setInvoiceAddress',
        'delivery_address' => 'setDeliveryAddress',
        'basket' => 'setBasket',
        'order_precheck_response' => 'setOrderPrecheckResponse'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'request_mode' => 'getRequestMode',
        'custom_reference' => 'getCustomReference',
        'personal_data' => 'getPersonalData',
        'proof_of_interest' => 'getProofOfInterest',
        'selected_payment_type' => 'getSelectedPaymentType',
        'payment_type_security' => 'getPaymentTypeSecurity',
        'invoice_address' => 'getInvoiceAddress',
        'delivery_address' => 'getDeliveryAddress',
        'basket' => 'getBasket',
        'order_precheck_response' => 'getOrderPrecheckResponse'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['request_mode'] = $data['request_mode'] ?? null;
        $this->container['custom_reference'] = $data['custom_reference'] ?? null;
        $this->container['personal_data'] = $data['personal_data'] ?? null;
        $this->container['proof_of_interest'] = $data['proof_of_interest'] ?? null;
        $this->container['selected_payment_type'] = $data['selected_payment_type'] ?? null;
        $this->container['payment_type_security'] = $data['payment_type_security'] ?? null;
        $this->container['invoice_address'] = $data['invoice_address'] ?? null;
        $this->container['delivery_address'] = $data['delivery_address'] ?? null;
        $this->container['basket'] = $data['basket'] ?? null;
        $this->container['order_precheck_response'] = $data['order_precheck_response'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['request_mode'] === null) {
            $invalidProperties[] = "'request_mode' can't be null";
        }
        if ($this->container['personal_data'] === null) {
            $invalidProperties[] = "'personal_data' can't be null";
        }
        if ($this->container['invoice_address'] === null) {
            $invalidProperties[] = "'invoice_address' can't be null";
        }
        if ($this->container['basket'] === null) {
            $invalidProperties[] = "'basket' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets request_mode
     *
     * @return \Axytos\FinancialServicesAPI\Client\Model\AxytosCommonPublicAPIEnumsPaymentControlRequestMode
     */
    public function getRequestMode()
    {
        return $this->container['request_mode'];
    }

    /**
     * Sets request_mode
     *
     * @param \Axytos\FinancialServicesAPI\Client\Model\AxytosCommonPublicAPIEnumsPaymentControlRequestMode $request_mode request_mode
     *
     * @return self
     */
    public function setRequestMode($request_mode)
    {
        $this->container['request_mode'] = $request_mode;

        return $this;
    }

    /**
     * Gets custom_reference
     *
     * @return string|null
     */
    public function getCustomReference()
    {
        return $this->container['custom_reference'];
    }

    /**
     * Sets custom_reference
     *
     * @param string|null $custom_reference custom_reference
     *
     * @return self
     */
    public function setCustomReference($custom_reference)
    {
        $this->container['custom_reference'] = $custom_reference;

        return $this;
    }

    /**
     * Gets personal_data
     *
     * @return \Axytos\FinancialServicesAPI\Client\Model\AxytosCommonPublicAPIModelsCommonCustomerDataRequestModel
     */
    public function getPersonalData()
    {
        return $this->container['personal_data'];
    }

    /**
     * Sets personal_data
     *
     * @param \Axytos\FinancialServicesAPI\Client\Model\AxytosCommonPublicAPIModelsCommonCustomerDataRequestModel $personal_data personal_data
     *
     * @return self
     */
    public function setPersonalData($personal_data)
    {
        $this->container['personal_data'] = $personal_data;

        return $this;
    }

    /**
     * Gets proof_of_interest
     *
     * @return \Axytos\FinancialServicesAPI\Client\Model\AxytosCommonPublicAPIEnumsProofOfInterest|null
     */
    public function getProofOfInterest()
    {
        return $this->container['proof_of_interest'];
    }

    /**
     * Sets proof_of_interest
     *
     * @param \Axytos\FinancialServicesAPI\Client\Model\AxytosCommonPublicAPIEnumsProofOfInterest|null $proof_of_interest proof_of_interest
     *
     * @return self
     */
    public function setProofOfInterest($proof_of_interest)
    {
        $this->container['proof_of_interest'] = $proof_of_interest;

        return $this;
    }

    /**
     * Gets selected_payment_type
     *
     * @return string|null
     */
    public function getSelectedPaymentType()
    {
        return $this->container['selected_payment_type'];
    }

    /**
     * Sets selected_payment_type
     *
     * @param string|null $selected_payment_type selected_payment_type
     *
     * @return self
     */
    public function setSelectedPaymentType($selected_payment_type)
    {
        $this->container['selected_payment_type'] = $selected_payment_type;

        return $this;
    }

    /**
     * Gets payment_type_security
     *
     * @return \Axytos\FinancialServicesAPI\Client\Model\AxytosCommonPublicAPIEnumsPaymentTypeSecurity|null
     */
    public function getPaymentTypeSecurity()
    {
        return $this->container['payment_type_security'];
    }

    /**
     * Sets payment_type_security
     *
     * @param \Axytos\FinancialServicesAPI\Client\Model\AxytosCommonPublicAPIEnumsPaymentTypeSecurity|null $payment_type_security payment_type_security
     *
     * @return self
     */
    public function setPaymentTypeSecurity($payment_type_security)
    {
        $this->container['payment_type_security'] = $payment_type_security;

        return $this;
    }

    /**
     * Gets invoice_address
     *
     * @return \Axytos\FinancialServicesAPI\Client\Model\AxytosCommonPublicAPIModelsCommonInvoiceAddress
     */
    public function getInvoiceAddress()
    {
        return $this->container['invoice_address'];
    }

    /**
     * Sets invoice_address
     *
     * @param \Axytos\FinancialServicesAPI\Client\Model\AxytosCommonPublicAPIModelsCommonInvoiceAddress $invoice_address invoice_address
     *
     * @return self
     */
    public function setInvoiceAddress($invoice_address)
    {
        $this->container['invoice_address'] = $invoice_address;

        return $this;
    }

    /**
     * Gets delivery_address
     *
     * @return \Axytos\FinancialServicesAPI\Client\Model\AxytosCommonPublicAPIModelsCommonDeliveryAddress|null
     */
    public function getDeliveryAddress()
    {
        return $this->container['delivery_address'];
    }

    /**
     * Sets delivery_address
     *
     * @param \Axytos\FinancialServicesAPI\Client\Model\AxytosCommonPublicAPIModelsCommonDeliveryAddress|null $delivery_address delivery_address
     *
     * @return self
     */
    public function setDeliveryAddress($delivery_address)
    {
        $this->container['delivery_address'] = $delivery_address;

        return $this;
    }

    /**
     * Gets basket
     *
     * @return \Axytos\FinancialServicesAPI\Client\Model\AxytosCommonPublicAPIModelsOrderBasket
     */
    public function getBasket()
    {
        return $this->container['basket'];
    }

    /**
     * Sets basket
     *
     * @param \Axytos\FinancialServicesAPI\Client\Model\AxytosCommonPublicAPIModelsOrderBasket $basket basket
     *
     * @return self
     */
    public function setBasket($basket)
    {
        $this->container['basket'] = $basket;

        return $this;
    }

    /**
     * Gets order_precheck_response
     *
     * @return \Axytos\FinancialServicesAPI\Client\Model\AxytosCommonPublicAPIModelsPaymentControlOrderPrecheckResponse|null
     */
    public function getOrderPrecheckResponse()
    {
        return $this->container['order_precheck_response'];
    }

    /**
     * Sets order_precheck_response
     *
     * @param \Axytos\FinancialServicesAPI\Client\Model\AxytosCommonPublicAPIModelsPaymentControlOrderPrecheckResponse|null $order_precheck_response order_precheck_response
     *
     * @return self
     */
    public function setOrderPrecheckResponse($order_precheck_response)
    {
        $this->container['order_precheck_response'] = $order_precheck_response;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


