<?php
/**
 * AxytosCommonPublicAPIEnumsProofOfInterest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Axytos\FinancialServicesAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Axytos API
 *
 * Note: Please provide proper values in \"Try it out\". See schemas and endpoint description for possible values. <br/>DateTimes should always be provided in UTC and with the timezone attached, see ISO-8601 (example: 2021-10-13T20:00:30Z)
 *
 * The version of the OpenAPI document: v1
 * Contact: 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Axytos\FinancialServicesAPI\Client\Model;
use \Axytos\FinancialServicesAPI\Client\ObjectSerializer;

/**
 * AxytosCommonPublicAPIEnumsProofOfInterest Class Doc Comment
 *
 * @category Class
 * @package  Axytos\FinancialServicesAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AxytosCommonPublicAPIEnumsProofOfInterest
{
    /**
     * Possible values of this enum
     */
    public const AAA = 'AAA';

    public const AAB = 'AAB';

    public const BAB = 'BAB';

    public const BAC = 'BAC';

    public const AAE = 'AAE';

    public const AAF = 'AAF';

    public const AAG = 'AAG';

    public const AAH = 'AAH';

    public const AAI = 'AAI';

    public const BAA = 'BAA';

    public const AAJ = 'AAJ';

    public const AAK = 'AAK';

    public const DAA = 'DAA';

    public const DAB = 'DAB';

    public const DAD = 'DAD';

    public const DAC = 'DAC';

    public const AAL = 'AAL';

    public const EAA = 'EAA';

    public const AAM = 'AAM';

    public const EAB = 'EAB';

    public const FAA = 'FAA';

    public const FAB = 'FAB';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::AAA,
            self::AAB,
            self::BAB,
            self::BAC,
            self::AAE,
            self::AAF,
            self::AAG,
            self::AAH,
            self::AAI,
            self::BAA,
            self::AAJ,
            self::AAK,
            self::DAA,
            self::DAB,
            self::DAD,
            self::DAC,
            self::AAL,
            self::EAA,
            self::AAM,
            self::EAB,
            self::FAA,
            self::FAB
        ];
    }
}


