<?php
/**
 * AxytosCommonPublicAPIModelsOrderOrderPreCheckRequestTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Axytos\FinancialServicesAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Axytos API
 *
 * Note: Please provide proper values in \"Try it out\". See schemas and endpoint description for possible values. <br/>DateTimes should always be provided in UTC and with the timezone attached, see ISO-8601 (example: 2021-10-13T20:00:30Z)
 *
 * The version of the OpenAPI document: v1
 * Contact: 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Axytos\FinancialServicesAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * AxytosCommonPublicAPIModelsOrderOrderPreCheckRequestTest Class Doc Comment
 *
 * @category    Class
 * @description AxytosCommonPublicAPIModelsOrderOrderPreCheckRequest
 * @package     Axytos\FinancialServicesAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class AxytosCommonPublicAPIModelsOrderOrderPreCheckRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "AxytosCommonPublicAPIModelsOrderOrderPreCheckRequest"
     */
    public function testAxytosCommonPublicAPIModelsOrderOrderPreCheckRequest()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "request_mode"
     */
    public function testPropertyRequestMode()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "custom_reference"
     */
    public function testPropertyCustomReference()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "personal_data"
     */
    public function testPropertyPersonalData()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "proof_of_interest"
     */
    public function testPropertyProofOfInterest()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "selected_payment_type"
     */
    public function testPropertySelectedPaymentType()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "payment_type_security"
     */
    public function testPropertyPaymentTypeSecurity()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "invoice_address"
     */
    public function testPropertyInvoiceAddress()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "delivery_address"
     */
    public function testPropertyDeliveryAddress()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "basket"
     */
    public function testPropertyBasket()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "order_precheck_response"
     */
    public function testPropertyOrderPrecheckResponse()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
