<?php
/**
 * CustomerDataApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Axytos\FinancialServicesAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Axytos API
 *
 * Note: Please provide proper values in \"Try it out\". See schemas and endpoint description for possible values. <br/>DateTimes should always be provided in UTC and with the timezone attached, see ISO-8601 (example: 2021-10-13T20:00:30Z)
 *
 * The version of the OpenAPI document: v1
 * Contact: 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Axytos\FinancialServicesAPI\Client\Test\Api;

use \Axytos\FinancialServicesAPI\Client\Configuration;
use \Axytos\FinancialServicesAPI\Client\ApiException;
use \Axytos\FinancialServicesAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * CustomerDataApiTest Class Doc Comment
 *
 * @category Class
 * @package  Axytos\FinancialServicesAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CustomerDataApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for apiV1CustomerDataUploadCustomerDataPost
     *
     * Upload a CSV file containing customer data with this endpoint..
     *
     */
    public function testApiV1CustomerDataUploadCustomerDataPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
