<?php
/**
 * PaymentsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Axytos\FinancialServicesAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Axytos API
 *
 * Note: Please provide proper values in \"Try it out\". See schemas and endpoint description for possible values. <br/>DateTimes should always be provided in UTC and with the timezone attached, see ISO-8601 (example: 2021-10-13T20:00:30Z)
 *
 * The version of the OpenAPI document: v1
 * Contact: 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Axytos\FinancialServicesAPI\Client\Test\Api;

use \Axytos\FinancialServicesAPI\Client\Configuration;
use \Axytos\FinancialServicesAPI\Client\ApiException;
use \Axytos\FinancialServicesAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PaymentsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Axytos\FinancialServicesAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PaymentsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for apiV1PaymentsInvoiceOrderCancelExternalOrderIdPost
     *
     * cancels an order that is not shipped yet.
     *
     */
    public function testApiV1PaymentsInvoiceOrderCancelExternalOrderIdPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1PaymentsInvoiceOrderConfirmPost
     *
     * transmits an order to the axytos platform.
     *
     */
    public function testApiV1PaymentsInvoiceOrderConfirmPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1PaymentsInvoiceOrderCreateInvoicePost
     *
     * creates a an invoice from a corresponding order.
     *
     */
    public function testApiV1PaymentsInvoiceOrderCreateInvoicePost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1PaymentsInvoiceOrderPaymentstateExternalOrderIdGet
     *
     * get the payment state for an existing order.
     *
     */
    public function testApiV1PaymentsInvoiceOrderPaymentstateExternalOrderIdGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1PaymentsInvoiceOrderPrecheckPost
     *
     * checks which payment types can be offered safely.
     *
     */
    public function testApiV1PaymentsInvoiceOrderPrecheckPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1PaymentsInvoiceOrderRefundPost
     *
     * can partially refund individual invoice items.
     *
     */
    public function testApiV1PaymentsInvoiceOrderRefundPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1PaymentsInvoiceOrderReportshippingPost
     *
     * reports the shipped positions.
     *
     */
    public function testApiV1PaymentsInvoiceOrderReportshippingPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1PaymentsInvoiceOrderReturnPost
     *
     * can return invoice positions.
     *
     */
    public function testApiV1PaymentsInvoiceOrderReturnPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1PaymentsInvoiceOrderTrackingInformationPost
     *
     * reports tracking information for shippings.
     *
     */
    public function testApiV1PaymentsInvoiceOrderTrackingInformationPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV1PaymentsInvoiceOrderUpdatePost
     *
     * Update an existing order.  Only possible, when no invoice is created yet..
     *
     */
    public function testApiV1PaymentsInvoiceOrderUpdatePost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
